FROM ubuntu:16.04
MAINTAINER Kent Knox <kent.knox@amd>

# Initialize the image we are working with
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y wget && \
    wget -qO - http://10.255.8.5/rocm/apt/debian/rocm.gpg.key | apt-key add - && \
    sh -c  "echo deb [arch=amd64] $DEB_ROCM_REPO xenial main > /etc/apt/sources.list.d/rocm.list" && \
    apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    rocm-dev \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# # Copy the debian package of hcc-lc into the container from host
# COPY *.deb /tmp/

# # Install the debian package, and print out contents of expected changed locations
# RUN dpkg -i /tmp/*.deb && \
#     rm -f /tmp/*.deb && \
#     printf "cat /etc/ld.so.conf.d/hipblas-dev.conf\n" && cat /etc/ld.so.conf.d/hipblas-dev.conf && \
#     printf "ls -la /opt/rocm/include\n" && ls -la /opt/rocm/include && \
#     printf "ls -la /opt/rocm/lib \n" && ls -la /opt/rocm/lib && \
#     printf "ls -la /opt/rocm/lib/cmake\n" && ls -la /opt/rocm/lib/cmake && \
#     printf "ls -la /opt/rocm/hipblas/include\n" && ls -la /opt/rocm/hipblas/include && \
#     printf "ls -la /opt/rocm/hipblas/lib\n" && ls -la /opt/rocm/hipblas/lib
